//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 5/24/2011 4:29:23 PM
namespace Logikos.Restoration.IdUtility.Gateway
{
    
    /// <summary>
    /// There are no comments for GatewayEntities in the schema.
    /// </summary>
    public partial class GatewayEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new GatewayEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public GatewayEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("OverviewCommon.GatewayModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Logikos.Restoration.IdUtility.Gateway", typeName.Substring(27)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Logikos.Restoration.IdUtility.Gateway", global::System.StringComparison.Ordinal))
            {
                return string.Concat("OverviewCommon.GatewayModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for SerialNumberTypes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SerialNumberType> SerialNumberTypes
        {
            get
            {
                if ((this._SerialNumberTypes == null))
                {
                    this._SerialNumberTypes = base.CreateQuery<SerialNumberType>("SerialNumberTypes");
                }
                return this._SerialNumberTypes;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SerialNumberType> _SerialNumberTypes;
        /// <summary>
        /// There are no comments for SerialNumbers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SerialNumber> SerialNumbers
        {
            get
            {
                if ((this._SerialNumbers == null))
                {
                    this._SerialNumbers = base.CreateQuery<SerialNumber>("SerialNumbers");
                }
                return this._SerialNumbers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SerialNumber> _SerialNumbers;
        /// <summary>
        /// There are no comments for Trackers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Tracker> Trackers
        {
            get
            {
                if ((this._Trackers == null))
                {
                    this._Trackers = base.CreateQuery<Tracker>("Trackers");
                }
                return this._Trackers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Tracker> _Trackers;
        /// <summary>
        /// There are no comments for SerialNumberTypes in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSerialNumberTypes(SerialNumberType serialNumberType)
        {
            base.AddObject("SerialNumberTypes", serialNumberType);
        }
        /// <summary>
        /// There are no comments for SerialNumbers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSerialNumbers(SerialNumber serialNumber)
        {
            base.AddObject("SerialNumbers", serialNumber);
        }
        /// <summary>
        /// There are no comments for Trackers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTrackers(Tracker tracker)
        {
            base.AddObject("Trackers", tracker);
        }
    }
    /// <summary>
    /// There are no comments for OverviewCommon.GatewayModel.SerialNumberType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SerialNumberTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class SerialNumberType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SerialNumberType object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SerialNumberType CreateSerialNumberType(int ID, string name)
        {
            SerialNumberType serialNumberType = new SerialNumberType();
            serialNumberType.Id = ID;
            serialNumberType.Name = name;
            return serialNumberType;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for SerialNumbers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SerialNumber> SerialNumbers
        {
            get
            {
                return this._SerialNumbers;
            }
            set
            {
                this._SerialNumbers = value;
                this.OnPropertyChanged("SerialNumbers");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SerialNumber> _SerialNumbers = new global::System.Data.Services.Client.DataServiceCollection<SerialNumber>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OverviewCommon.GatewayModel.SerialNumber in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SerialNumbers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class SerialNumber : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SerialNumber object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="serialNumberTypeId">Initial value of SerialNumberTypeId.</param>
        /// <param name="theSerialNumber">Initial value of TheSerialNumber.</param>
        /// <param name="batchDate">Initial value of BatchDate.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SerialNumber CreateSerialNumber(int ID, int serialNumberTypeId, string theSerialNumber, global::System.DateTime batchDate)
        {
            SerialNumber serialNumber = new SerialNumber();
            serialNumber.Id = ID;
            serialNumber.SerialNumberTypeId = serialNumberTypeId;
            serialNumber.TheSerialNumber = theSerialNumber;
            serialNumber.BatchDate = batchDate;
            return serialNumber;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property SerialNumberTypeId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SerialNumberTypeId
        {
            get
            {
                return this._SerialNumberTypeId;
            }
            set
            {
                this.OnSerialNumberTypeIdChanging(value);
                this._SerialNumberTypeId = value;
                this.OnSerialNumberTypeIdChanged();
                this.OnPropertyChanged("SerialNumberTypeId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SerialNumberTypeId;
        partial void OnSerialNumberTypeIdChanging(int value);
        partial void OnSerialNumberTypeIdChanged();
        /// <summary>
        /// There are no comments for Property TheSerialNumber in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TheSerialNumber
        {
            get
            {
                return this._TheSerialNumber;
            }
            set
            {
                this.OnTheSerialNumberChanging(value);
                this._TheSerialNumber = value;
                this.OnTheSerialNumberChanged();
                this.OnPropertyChanged("TheSerialNumber");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TheSerialNumber;
        partial void OnTheSerialNumberChanging(string value);
        partial void OnTheSerialNumberChanged();
        /// <summary>
        /// There are no comments for Property TrackerId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> TrackerId
        {
            get
            {
                return this._TrackerId;
            }
            set
            {
                this.OnTrackerIdChanging(value);
                this._TrackerId = value;
                this.OnTrackerIdChanged();
                this.OnPropertyChanged("TrackerId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _TrackerId;
        partial void OnTrackerIdChanging(global::System.Nullable<int> value);
        partial void OnTrackerIdChanged();
        /// <summary>
        /// There are no comments for Property BatchDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime BatchDate
        {
            get
            {
                return this._BatchDate;
            }
            set
            {
                this.OnBatchDateChanging(value);
                this._BatchDate = value;
                this.OnBatchDateChanged();
                this.OnPropertyChanged("BatchDate");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _BatchDate;
        partial void OnBatchDateChanging(global::System.DateTime value);
        partial void OnBatchDateChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for SerialNumberType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SerialNumberType SerialNumberType
        {
            get
            {
                return this._SerialNumberType;
            }
            set
            {
                this._SerialNumberType = value;
                this.OnPropertyChanged("SerialNumberType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SerialNumberType _SerialNumberType;
        /// <summary>
        /// There are no comments for Tracker in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Tracker Tracker
        {
            get
            {
                return this._Tracker;
            }
            set
            {
                this._Tracker = value;
                this.OnPropertyChanged("Tracker");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Tracker _Tracker;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OverviewCommon.GatewayModel.Tracker in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Trackers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Tracker : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Tracker object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="mobileId">Initial value of MobileId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Tracker CreateTracker(int ID, string mobileId)
        {
            Tracker tracker = new Tracker();
            tracker.Id = ID;
            tracker.MobileId = mobileId;
            return tracker;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property MobileId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MobileId
        {
            get
            {
                return this._MobileId;
            }
            set
            {
                this.OnMobileIdChanging(value);
                this._MobileId = value;
                this.OnMobileIdChanged();
                this.OnPropertyChanged("MobileId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MobileId;
        partial void OnMobileIdChanging(string value);
        partial void OnMobileIdChanged();
        /// <summary>
        /// There are no comments for Property ClientId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> ClientId
        {
            get
            {
                return this._ClientId;
            }
            set
            {
                this.OnClientIdChanging(value);
                this._ClientId = value;
                this.OnClientIdChanged();
                this.OnPropertyChanged("ClientId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _ClientId;
        partial void OnClientIdChanging(global::System.Nullable<int> value);
        partial void OnClientIdChanged();
        /// <summary>
        /// There are no comments for Property Comment in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comment
        {
            get
            {
                return this._Comment;
            }
            set
            {
                this.OnCommentChanging(value);
                this._Comment = value;
                this.OnCommentChanged();
                this.OnPropertyChanged("Comment");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comment;
        partial void OnCommentChanging(string value);
        partial void OnCommentChanged();
        /// <summary>
        /// There are no comments for SerialNumbers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<SerialNumber> SerialNumbers
        {
            get
            {
                return this._SerialNumbers;
            }
            set
            {
                this._SerialNumbers = value;
                this.OnPropertyChanged("SerialNumbers");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<SerialNumber> _SerialNumbers = new global::System.Data.Services.Client.DataServiceCollection<SerialNumber>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
