//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logikos.Restoration.IdUtility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Logikos.Restoration.IdUtility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway service URI not found. Add key &apos;{0}&apos; to application configuration file via Settings.settings..
        /// </summary>
        internal static string GatewayUriAppSettingNotFound {
            get {
                return ResourceManager.GetString("GatewayUriAppSettingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.  {0}.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Error.
        /// </summary>
        internal static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains FCC ID: W7Z-ICP0.
        /// </summary>
        internal static string LabelFccId {
            get {
                return ResourceManager.GetString("LabelFccId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview {0} {1}.
        /// </summary>
        internal static string LabelLineOneFormat {
            get {
                return ResourceManager.GetString("LabelLineOneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string LabelNode {
            get {
                return ResourceManager.GetString("LabelNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://overview.logikos.com.
        /// </summary>
        internal static string LabelOverviewUri {
            get {
                return ResourceManager.GetString("LabelOverviewUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string LabelTag {
            get {
                return ResourceManager.GetString("LabelTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        internal static string LabelTagVersionNumber {
            get {
                return ResourceManager.GetString("LabelTagVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load {0} to database?\nThis operation may take a while and cannot be undone with this utility..
        /// </summary>
        internal static string LoadToDatabaseConfirmation {
            get {
                return ResourceManager.GetString("LoadToDatabaseConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Load Confirmation.
        /// </summary>
        internal static string LoadToDatabaseConfirmationCaption {
            get {
                return ResourceManager.GetString("LoadToDatabaseConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found..
        /// </summary>
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.  File may be missing, in the wrong format or empty..
        /// </summary>
        internal static string NoRecordsFoundInFile {
            get {
                return ResourceManager.GetString("NoRecordsFoundInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing failed.  {0}.
        /// </summary>
        internal static string PrintError {
            get {
                return ResourceManager.GetString("PrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Error.
        /// </summary>
        internal static string PrintErrorCaption {
            get {
                return ResourceManager.GetString("PrintErrorCaption", resourceCulture);
            }
        }
    }
}
